apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mkdevops-online-certificate
  namespace: cert-manager
spec:
  secretName: mkdevops-online-certificate-tls
  issuerRef:
    name: letsencrypt-staging-issuer
    kind: ClusterIssuer
  commonName: mkdevops.online
  dnsNames:
  - mkdevops.online
  - '*.mkdevops.online'
