---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: maciejkulik@outlook.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: maciejkulik@outlook.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token