apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: dev
  sources:
  - chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      releaseName: hashicorp-vault
      valueFiles:
      - $values/infrastructure/security/hashicorp-vault/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/MJKulik/Homelab.git
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true