server:
   affinity: ""
   ha:
     enabled: true
     raft: 
       enabled: true
       setNodeId: true
       config: |
            cluster_name = "vault-integrated-storage"
            storage "raft" {
               path    = "/vault/data/"
            }

            listener "tcp" {
               address = "[::]:8200"
               cluster_address = "[::]:8201"
               tls_disable = "true"
            }
            service_registration "kubernetes" {}

# This configures the volume used for storing Vault data when not using external storage such as Consul.
dataStorage:
  #  Enables a persistent volume to be created for storing Vault data when not using an external storage service.
  enabled: true
  # Size of the volume to be created for Vault's data storage when not using an external storage service.
  size: 8Gi
  # Name of the storage class to use when creating the data storage volume.
  storageClass: longhorn
  # Access Mode of the storage device being used for the PVC
  accessMode: ReadWriteOnce
  # Configures the path in the Vault pod where the audit storage will be mounted.
  mountPath: /vault/data
auditStorage:
  #  Enables a persistent volume to be created for storing Vault data when not using an external storage service.
  enabled: true
  # Size of the volume to be created for Vault's data storage when not using an external storage service.
  size: 8Gi
  # Name of the storage class to use when creating the data storage volume.
  storageClass: longhorn
  # Access Mode of the storage device being used for the PVC
  accessMode: ReadWriteOnce
  # Configures the path in the Vault pod where the audit storage will be mounted.
  mountPath: /vault/audit