apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: dev
  sources:
  - chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.23
    helm:
      releaseName: argo-cd
      valueFiles:
      - $values/infrastructure/automation/argo-cd/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/MJKulik/Homelab.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/MJKulik/Homelab.git
    targetRevision: main
    path: infrastructure/automation/argo-cd/config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true