apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-infrastructure
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: infrastructure
    repoURL: https://github.com/MJKulik/Homelab.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true