apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: dev
  source:
    chart: cilium
    repoURL: https://helm.cilium.io/
    targetRevision: 1.17.2
    helm:
      releaseName: cilium
      valueFiles:
      - values.yaml
    #   ignoreMissingValueFiles: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true