apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: dev
  sources:
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: 1.17.2
      helm:
        releaseName: cilium
        valueFiles:
        - $values/cilium-values.yaml
    #     ignoreMissingValueFiles: true
    - repoURL: https://github.com/MJKulik/Homelab.git
      targetRevision: main
      path: /infrastructure/networking/cilium/
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  source:
    path: cilium