ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/network/concepts/ipam/
  mode: "kubernetes"

# Replace default kube-proxy
kubeProxyReplacement: true

# -- (string) Kubernetes service host - use "auto" for automatic lookup from the cluster-info ConfigMap
# localhost wont work after pure installation cuz coreDNS pending state use IP and proper port
k8sServiceHost: "localhost"

# -- (string) Kubernetes service port
k8sServicePort: "7445"

# -- Configure cgroup related configuration
cgroup:
  autoMount:
    # -- Enable auto mount of cgroup2 filesystem.
    # When `autoMount` is enabled, cgroup2 filesystem is mounted at
    # `cgroup.hostRoot` path on the underlying host and inside the cilium agent pod.
    # If users disable `autoMount`, it's expected that users have mounted
    # cgroup2 filesystem at the specified `cgroup.hostRoot` volume, and then the
    # volume will be mounted inside the cilium agent pod at the same path.
    enabled: false
    # -- Init Container Cgroup Automount resource limits & requests
  # -- Configure cgroup root where cgroup2 filesystem is mounted on the host (see also: `cgroup.autoMount`)
  hostRoot: /sys/fs/cgroup
  
securityContext:
  capabilities:
    # -- Capabilities for the `cilium-agent` container
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState:
      [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]