apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: dev
  sources:
  - chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.11.3
    helm:
      releaseName: grafana
      valueFiles:
      - $values/infrastructure/monitoring/grafana/values.yaml
      ignoreMissingValueFiles: true
  - repoURL: https://github.com/MJKulik/Homelab.git
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    