apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argo-cd
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.home.mkdevops.online
  issuerRef:
    name: letsencrypt-production-issuer
    kind: ClusterIssuer
